### ISSUE TITLE
关于博客跨域的疑问

### ISSUE THREAD

**Issue by clearJSer** [shenghy/react_blog#1]
胖哥，中台跨域设置的：
` config.cors = {
    origin: 'http://127.0.0.1:3000', // 只允许这个域进行访问接口
    credentials: true, // 开启认证
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS',
  };`
当前台博客 和 后台admin 项目同时启动部署时，两个项目端口肯定不一致吧？这个支持两个端口的跨域是怎么实现的啊？

**Comment by xiacao** [comment]
service/config/config.default.js

中  的  config.security、config.cors替换成如下
```js
  config.security = {
    csrf: { enable: false },
    //1、以下加入需要跨域的所有白名单
    domainWhiteList: ['http://localhost:3000', 'http://localhost:3001'],
  };

  config.cors = {
     // 2、更改origin
     origin: ctx => ctx.get('origin'),
     credentials: true,  //允许Cookie可以跨域
     allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS'
  };
```

**Comment by clearJSer** [comment]
> service/config/config.default.js
> 
> 中 的 config.security、config.cors替换成如下
> 
> ```js
>   config.security = {
>     csrf: { enable: false },
>     //1、以下加入需要跨域的所有白名单
>     domainWhiteList: ['http://localhost:3000', 'http://localhost:3001'],
>   };
> 
>   config.cors = {
>      // 2、更改origin
>      origin: ctx => ctx.get('origin'),
>      credentials: true,  //允许Cookie可以跨域
>      allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS'
>   };
> ```

谢谢大佬 加个微信吗？

**Comment by clearJSer** [comment]
非常感谢 ，效果很好
